name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
# assignees:
#   - bbonkr
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  # - type: input
  #   id: contact
  #   attributes:
  #     label: Contact Details
  #     description: How can we get in touch with you if we need more info?
  #     placeholder: ex. email@example.com
  #   validations:
  #     required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
      value: |
          - OS:
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
