name: "Build"

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #[macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js, Npm
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build:prod
      - name: Pack
        run: npm run pack
      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'packages/Rename Setup*'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Tag
        uses: anothrNick/github-tag-action@1.26.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
